export const initialPieceState = {
  '0': {
    '0': null,
    '1': null,
    '2': null,
    '3': null,
    '4': null,
    '5': null,
    '6': null,
    '7': null,
    '8': null,
    '9': null,
    '10': null,
    '11': null,
  },
  '1': {
    '0': null,
    '1': null,
    '2': null,
    '3': null,
    '4': null,
    '5': null,
    '6': null,
    '7': {
      name: "king",
      symbol: "king"
    },
    '8': null,
    '9': null,
    '10': null,
    '11': null,
  },
  '2': {
    '0': null,
    '1': null,
    '2': {
      name: 'knight',
      symbol: 'knight'
    },
    '3': null,
    '4': null,
    '5': null,
    '6': {
      name: 'hunter',
      symbol: 'hunter'
    },
    '7': null,
    '8': null,
    '9': null,
    '10': null,
    '11': null,
  },
  '3': {
    '0': null,
    '1': null,
    '2': null,
    '3': null,
    '4': {
      name: 'rook',
      symbol: 'rook'
    },
    '5': null,
    '6': null,
    '7': null,
    '8': null,
    '9': null,
    '10': null,
    '11': null,
  },
  '4': {
    '0': null,
    '1': null,
    '2': null,
    '3': null,
    '4': {
      name: 'nightrider',
      symbol: 'nightrider'
    },
    '5': null,
    '6': null,
    '7': null,
    '8': null,
    '9': null,
    '10': null,
    '11': null,
  },
  '5': {
    '0': null,
    '1': null,
    '2': null,
    '3': null,
    '4': null,
    '5': null,
    '6': {
      name: "pawn",
      symbol: "pawn"
    },
    '7': null,
    '8': null,
    '9': null,
    '10': null,
    '11': null,
  },
  '6': {
    '0': null,
    '1': null,
    '2': {
      name: 'unicorn',
      symbol: 'unicorn'
    },
    '3': null,
    '4': null,
    '5': null,
    '6': null,
    '7': null,
    '8': {
      name: 'skiprook',
      symbol: 'skiprook'
    },
    '9': null,
    '10': null,
    '11': null,
  },
  '7': {
    '0': null,
    '1': null,
    '2': null,
    '3': null,
    '4': null,
    '5': {
      name: 'plus',
      symbol: 'plus'
    },
    '6': null,
    '7': null,
    '8': null,
    '9': null,
    '10': null,
    '11': null,
  },
  '8': {
    '0': null,
    '1': null,
    '2': null,
    '3': {
      name: 'nurse',
      symbol: 'nurse'
    },
    '4': null,
    '5': null,
    '6': null,
    '7': null,
    '8': null,
    '9': null,
    '10': null,
    '11': null,
  },
  '9': {
    '0': null,
    '1': null,
    '2': {
      name: 'elephant',
      symbol: 'elephant'
    },
    '3': null,
    '4': null,
    '5': null,
    '6': null,
    '7': null,
    '8': null,
    '9': null,
    '10': null,
    '11': null,
  },
  '10': {
    '0': null,
    '1': null,
    '2': null,
    '3': null,
    '4': {
      name: 'queen',
      symbol: 'queen'
    },
    '5': null,
    '6': null,
    '7': null,
    '8': null,
    '9': null,
    '10': null,
    '11': null,
  },
  '11': {
    '0': null,
    '1': null,
    '2': null,
    '3': null,
    '4': null,
    '5': null,
    '6': null,
    '7': null,
    '8': null,
    '9': null,
    '10': null,
    '11': null,
  },
};

export const initialSquareState = {
  '0': {
    '0': null,
    '1': null,
    '2': null,
    '3': null,
    '4': null,
    '5': null,
    '6': null,
    '7': null,
    '8': null,
    '9': null,
    '10': null,
    '11': null,
  },
  '1': {
    '0': null,
    '1': null,
    '2': null,
    '3': null,
    '4': null,
    '5': null,
    '6': null,
    '7': null,
    '8': null,
    '9': null,
    '10': null,
    '11': null,
  },
  '2': {
    '0': null,
    '1': null,
    '2': null,
    '3': null,
    '4': null,
    '5': null,
    '6': null,
    '7': null,
    '8': null,
    '9': null,
    '10': null,
    '11': null,
  },
  '3': {
    '0': null,
    '1': null,
    '2': null,
    '3': null,
    '4': null,
    '5': null,
    '6': null,
    '7': null,
    '8': null,
    '9': null,
    '10': null,
    '11': null,
  },
  '4': {
    '0': null,
    '1': null,
    '2': null,
    '3': null,
    '4': null,
    '5': null,
    '6': null,
    '7': null,
    '8': null,
    '9': null,
    '10': null,
    '11': null,
  },
  '5': {
    '0': null,
    '1': null,
    '2': null,
    '3': null,
    '4': null,
    '5': null,
    '6': null,
    '7': null,
    '8': null,
    '9': null,
    '10': null,
    '11': null,
  },
  '6': {
    '0': null,
    '1': null,
    '2': null,
    '3': null,
    '4': null,
    '5': null,
    '6': null,
    '7': null,
    '8': null,
    '9': null,
    '10': null,
    '11': null,
  },
  '7': {
    '0': null,
    '1': null,
    '2': null,
    '3': null,
    '4': null,
    '5': null,
    '6': null,
    '7': null,
    '8': null,
    '9': null,
    '10': null,
    '11': null,
  },
  '8': {
    '0': null,
    '1': null,
    '2': null,
    '3': null,
    '4': null,
    '5': null,
    '6': null,
    '7': null,
    '8': null,
    '9': null,
    '10': null,
    '11': null,
  },
  '9': {
    '0': null,
    '1': null,
    '2': null,
    '3': null,
    '4': null,
    '5': null,
    '6': null,
    '7': null,
    '8': null,
    '9': null,
    '10': null,
    '11': null,
  },
  '10': {
    '0': null,
    '1': null,
    '2': null,
    '3': null,
    '4': null,
    '5': null,
    '6': null,
    '7': null,
    '8': null,
    '9': null,
    '10': null,
    '11': null,
  },
  '11': {
    '0': null,
    '1': null,
    '2': null,
    '3': null,
    '4': null,
    '5': null,
    '6': null,
    '7': null,
    '8': null,
    '9': null,
    '10': null,
    '11': null,
  },
};