export const initialPieceState = {
  '0': {
    '0': null,
    '1': null,
    '2': null,
    '3': {
      name: 'kraken',
      symbol: 'kraken'
    },
    '4': null,
    '5': null,
    '6': null,
    '7': null,
    '8': null,
    '9': null,
    '10': null,
    '11': null,
  },
  '1': {
    '0': null,
    '1': null,
    '2': null,
    '3': null,
    '4': null,
    '5': null,
    '6': null,
    '7': {
      name: "moon",
      symbol: "moon"
    },
    '8': null,
    '9': null,
    '10': null,
    '11': null,
  },
  '2': {
    '0': null,
    '1': null,
    '2': {
      name: 'knight',
      symbol: 'knight'
    },
    '3': null,
    '4': null,
    '5': null,
    '6': {
      name: 'hunter',
      symbol: 'hunter'
    },
    '7': null,
    '8': null,
    '9': null,
    '10': null,
    '11': null,
  },
  '3': {
    '0': null,
    '1': null,
    '2': null,
    '3': null,
    '4': {
      name: 'ship',
      symbol: 'ship'
    },
    '5': null,
    '6': null,
    '7': null,
    '8': null,
    '9': null,
    '10': null,
    '11': null,
  },
  '4': {
    '0': null,
    '1': null,
    '2': null,
    '3': null,
    '4': {
      name: 'nightrider',
      symbol: 'nightrider'
    },
    '5': null,
    '6': null,
    '7': null,
    '8': null,
    '9': null,
    '10': null,
    '11': null,
  },
  '5': {
    '0': null,
    '1': null,
    '2': null,
    '3': null,
    '4': null,
    '5': null,
    '6': null,
    '7': null,
    '8': {
      name: 'bugeyedmonster',
      symbol: 'bugeyedmonster'
    },
    '9': null,
    '10': null,
    '11': null,
  },
  '6': {
    '0': null,
    '1': null,
    '2': {
      name: 'reflector',
      symbol: 'reflector'
    },
    '3': null,
    '4': null,
    '5': null,
    '6': null,
    '7': null,
    '8': {
      name: 'skiprook',
      symbol: 'skiprook'
    },
    '9': null,
    '10': null,
    '11': null,
  },
  '7': {
    '0': null,
    '1': null,
    '2': null,
    '3': null,
    '4': null,
    '5': {
      name: 'plus',
      symbol: 'plus'
    },
    '6': null,
    '7': null,
    '8': {
      name: 'deer',
      symbol: 'deer'
    },
    '9': null,
    '10': null,
    '11': null,
  },
  '8': {
    '0': null,
    '1': null,
    '2': null,
    '3': {
      name: 'rose',
      symbol: 'rose'
    },
    '4': null,
    '5': null,
    '6': null,
    '7': null,
    '8': null,
    '9': null,
    '10': null,
    '11': null,
  },
  '9': {
    '0': null,
    '1': null,
    '2': {
      name: 'elephant',
      symbol: 'elephant'
    },
    '3': null,
    '4': null,
    '5': null,
    '6': null,
    '7': null,
    '8': null,
    '9': null,
    '10': null,
    '11': null,
  },
  '10': {
    '0': null,
    '1': null,
    '2': null,
    '3': null,
    '4': {
      name: 'queen',
      symbol: 'queen'
    },
    '5': null,
    '6': null,
    '7': null,
    '8': null,
    '9': null,
    '10': null,
    '11': null,
  },
  '11': {
    '0': null,
    '1': null,
    '2': null,
    '3': null,
    '4': null,
    '5': null,
    '6': null,
    '7': null,
    '8': null,
    '9': null,
    '10': null,
    '11': null,
  },
};

export const initialSquareState = {
  '0': {
    '0': null,
    '1': null,
    '2': null,
    '3': null,
    '4': null,
    '5': null,
    '6': null,
    '7': null,
    '8': null,
    '9': null,
    '10': null,
    '11': null,
  },
  '1': {
    '0': null,
    '1': null,
    '2': null,
    '3': null,
    '4': null,
    '5': null,
    '6': null,
    '7': null,
    '8': null,
    '9': null,
    '10': null,
    '11': null,
  },
  '2': {
    '0': null,
    '1': null,
    '2': null,
    '3': null,
    '4': null,
    '5': null,
    '6': null,
    '7': null,
    '8': null,
    '9': null,
    '10': null,
    '11': null,
  },
  '3': {
    '0': null,
    '1': null,
    '2': null,
    '3': null,
    '4': null,
    '5': null,
    '6': null,
    '7': null,
    '8': null,
    '9': null,
    '10': null,
    '11': null,
  },
  '4': {
    '0': null,
    '1': null,
    '2': null,
    '3': null,
    '4': null,
    '5': null,
    '6': null,
    '7': null,
    '8': null,
    '9': null,
    '10': null,
    '11': null,
  },
  '5': {
    '0': null,
    '1': null,
    '2': null,
    '3': null,
    '4': null,
    '5': null,
    '6': null,
    '7': null,
    '8': null,
    '9': null,
    '10': null,
    '11': null,
  },
  '6': {
    '0': null,
    '1': null,
    '2': null,
    '3': null,
    '4': null,
    '5': null,
    '6': null,
    '7': null,
    '8': null,
    '9': null,
    '10': null,
    '11': null,
  },
  '7': {
    '0': null,
    '1': null,
    '2': null,
    '3': null,
    '4': null,
    '5': null,
    '6': null,
    '7': null,
    '8': null,
    '9': null,
    '10': null,
    '11': null,
  },
  '8': {
    '0': null,
    '1': null,
    '2': null,
    '3': null,
    '4': null,
    '5': null,
    '6': null,
    '7': null,
    '8': null,
    '9': null,
    '10': null,
    '11': null,
  },
  '9': {
    '0': null,
    '1': null,
    '2': null,
    '3': null,
    '4': null,
    '5': null,
    '6': null,
    '7': null,
    '8': null,
    '9': null,
    '10': null,
    '11': null,
  },
  '10': {
    '0': null,
    '1': null,
    '2': null,
    '3': null,
    '4': null,
    '5': null,
    '6': null,
    '7': null,
    '8': null,
    '9': null,
    '10': null,
    '11': null,
  },
  '11': {
    '0': null,
    '1': null,
    '2': null,
    '3': null,
    '4': null,
    '5': null,
    '6': null,
    '7': null,
    '8': null,
    '9': null,
    '10': null,
    '11': null,
  },
};